### ISSUE TITLE
Form doesn't validate

### ISSUE THREAD

**Issue by steveamaza** [PaystackHQ/Wordpress-Payment-forms-for-Paystack#20]
Form doesn't validate for required fields before Paystack pops up i.e. PaystackPop will load even if required fields are empty

**Comment by Kendysond** [comment]
https://github.com/PaystackHQ/Wordpress-Payment-forms-for-Paystack/tree/348c0942f8184f51e4d12f9ab570c57445d00cc1
Fixed

**Comment by steveamaza** [comment]
Hello @Kendysond, tested and it still doesn't validate. Can you let me know if I am doing something wrong?
